### ISSUE TITLE
Qt 5.9 Compatibility

### ISSUE THREAD

**Issue by j-o** [cginternals/qmltoolbox#27]
I get the following errors when trying to run gloperate-viewer:
```
QQmlApplicationEngine failed to load component
file:///E:/projects/gloperate.git/data/gloperate/qml/Viewer.qml:304 Type PropertyEditor unavailable
file:///E:/projects/qmltoolbox.git/data/qmltoolbox/qml/QmlToolbox/PropertyEditor/PropertyEditor.qml:143 Type EditorProxy unavailable
file:///E:/projects/qmltoolbox.git/data/qmltoolbox/qml/QmlToolbox/PropertyEditor/EditorProxy.qml:58 Type EditorNumber unavailable
file:///E:/projects/qmltoolbox.git/data/qmltoolbox/qml/QmlToolbox/PropertyEditor/EditorNumber.qml:19 Type Slider unavailable
file:///E:/projects/qmltoolbox.git/data/qmltoolbox/qml/QmlToolbox/Controls/Slider.qml:18 Cannot override FINAL property
```

This is because Qt 5.9 introduced a `live` property for the `Slider` type (cf. http://doc.qt.io/qt-5/qml-qtquick-controls2-slider.html#live-prop), which is declared final.
I don't know if there are any further incompatibilities.

Using Qt 5.9.1 on Visual Studio 2017 Win64

**Comment by Jopyth** [comment]
Additionally there are some minor alignment issues in a ComboBox, but everything else (except the incompatible slider) still seems to work.
